//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AoEAiTools.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AoEAiTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die true
        ///false
        ///event-detected
        ///taunt-detected
        ///timer-triggered
        ///cheats-enabled
        ///death-match-game
        ///difficulty
        ///game-time
        ///map-size
        ///map-type
        ///player-computer
        ///player-human
        ///player-in-game
        ///player-resigned
        ///player-valid
        ///population-cap
        ///regicide-game
        ///starting-age
        ///starting-resources
        ///victory-condition
        ///can-buy-commodity
        ///can-sell-commodity
        ///commodity-buying-price
        ///commodity-selling-price
        ///players-tribute
        ///players-tribute-memory
        ///can-build-gate-with-escrow
        ///can-build-wall-with-escrow
        ///can-build-with-escrow
        ///can [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Commands {
            get {
                return ResourceManager.GetString("Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die dark-age
        ///feudal-age
        ///castle-age
        ///imperial-age
        ///post-imperial-age
        ///
        ///archery-range
        ///barracks
        ///blacksmith
        ///bombard-tower
        ///castle
        ///dock
        ///farm
        ///fish-trap
        ///guard-tower
        ///house
        ///keep
        ///lumber-camp
        ///market
        ///mill
        ///mining-camp
        ///monastery
        ///outpost
        ///siege-workshop
        ///stable
        ///town-center
        ///university
        ///watch-tower
        ///wonder
        ///
        ///briton
        ///byzantine
        ///celtic
        ///chinese
        ///frankish
        ///gothic
        ///japanese
        ///mongol
        ///persian
        ///saracen
        ///teutonic
        ///turkish
        ///viking
        ///
        ///easiest
        ///easy
        ///moderate
        ///hard
        ///hardest
        ///
        ///ability-to-dodge-missiles
        ///ability-to-mai [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Identifiers {
            get {
                return ResourceManager.GetString("Identifiers", resourceCulture);
            }
        }
    }
}
